AWSTemplateFormatVersion: '2010-09-09'
Description: Using AWS CloudFormation to model and provision AWS Glue Workflows

Parameters:
  GlueWorkflowName:
    Type: String
    Description: Glue workflow that tracks all triggers, jobs, crawlers as a single entity
    Default: dav_wc_working_capital_summary_workflow_cfn

  GlueRoleName:
    Type: String
    Description: IAM role for AWS Glue Job
    Default: AWSGlueServiceRole-test
    AllowedValues:
      - AWSGlueServiceRole-test
      - devrole
      - stgrole
      - prdrole

  GlueConnection:
    Type: String
    Description: Data Connection for AWS Glue Job
    Default: testconnection
    AllowedValues:
      - testconnection
      - devconnection
      - stgconnection
      - prdconnection

  BucketName:
    Type: String
    Description: Bucket to store data
    Default: rajkumarasohancloudformationbucket
    AllowedValues:
      - rajkumarasohancloudformationbucket
      - devbucket
      - stgbucket
      - prdbucket

Resources:
  # Glue Workflow
  workingcapitalsummaryworkflow:
    Type: 'AWS::Glue::Workflow'
    Properties:
      Description: Glue workflow that tracks specified triggers and jobs as a single entity
      Name: !Ref GlueWorkflowName

  # Glue Triggers
  checksummaryrefreshtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - workingcapitalsummaryworkflow
      - checksummaryrefresh
    Properties:
      Name: dav_wc_check_summary_refresh_trigger_cfn
      Type: ON_DEMAND
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: dav_wc_check_summary_refresh

  loadonpremtos3HFMLEGALENTITYtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - checksummaryrefreshtrigger
      - loadonpremtos3HFMLEGALENTITY
    Properties:
      Name: dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY_trigger_cfn
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY
      Predicate:
        Conditions:
          - JobName: dav_wc_check_summary_refresh
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loads3toauroraHFMLEGALENTITYtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loadonpremtos3HFMLEGALENTITYtrigger
      - loads3toauroraHFMLEGALENTITY
    Properties:
      Name: dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY_trigger_cfn
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY
      Predicate:
        Conditions:
          - JobName: dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loadonpremtos3EXTHFM312DATAtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loads3toauroraHFMLEGALENTITYtrigger
      - loadonpremtos3EXTHFM312DATA
    Properties:
      Name: dav_wc_load_onprem_to_s3_EXT_HFM312_DATA_trigger_cfn
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: dav_wc_load_onprem_to_s3_EXT_HFM312_DATA
      Predicate:
        Conditions:
          - JobName: dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loads3toauroraEXTHFM312DATAtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loadonpremtos3EXTHFM312DATAtrigger
      - loads3toauroraEXTHFM312DATA
    Properties:
      Name: dav_wc_load_s3_to_aurora_EXT_HFM312_DATA_trigger_cfn
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: dav_wc_load_s3_to_aurora_EXT_HFM312_DATA
      Predicate:
        Conditions:
          - JobName: dav_wc_load_onprem_to_s3_EXT_HFM312_DATA
            LogicalOperator: EQUALS
            State: SUCCEEDED

  # Glue Jobs
  checksummaryrefresh:
    Type: AWS::Glue::Job
    Properties:
      Name: dav_wc_check_summary_refresh
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_check_summary_refresh.py
      GlueVersion: "4.0"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      NumberOfWorkers: 2
      WorkerType: G.1X
      DefaultArguments:  
        "--job-bookmark-option": "job-bookmark-disable"
        "--bucket_name": !Sub ${BucketName}
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_check_summary_refresh.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/scripts/dav_wc_check_summary_refresh.whl
        "--extra-jars": !Sub s3://${BucketName}/jdbc/dav_wc_check_summary_refresh.jar

  loadonpremtos3HFMLEGALENTITY:
    Type: AWS::Glue::Job
    Properties:
      Name: dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Sub ${BucketName}
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY.whl

  loads3toauroraHFMLEGALENTITY:
    Type: AWS::Glue::Job
    Properties:
      Name: dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Sub ${BucketName}
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY.whl

  loadonpremtos3EXTHFM312DATA:
    Type: AWS::Glue::Job
    Properties:
      Name: dav_wc_load_onprem_to_s3_EXT_HFM312_DATA
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_EXT_HFM312_DATA.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Sub ${BucketName}
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_onprem_to_s3_EXT_HFM312_DATA.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_EXT_HFM312_DATA.whl

  loads3toauroraEXTHFM312DATA:
    Type: AWS::Glue::Job
    Properties:
      Name: dav_wc_load_s3_to_aurora_EXT_HFM312_DATA
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_EXT_HFM312_DATA.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Sub ${BucketName}
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_s3_to_aurora_EXT_HFM312_DATA.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_EXT_HFM312_DATA.whl
