AWSTemplateFormatVersion: '2010-09-09'
Description: Using AWS CloudFormation to model and provision AWS Glue Workflows

Parameters:
  GlueWorkflowName:
    Type: String
    Description: Glue workflow that tracks all triggers, jobs, crawlers as a single entity
    AllowedValues:
      - dav_wc_working_capital_summary_workflow_cfn
      - dav_wc_working_capital_summary_workflow_cfn_prd

  GlueTrigger1:
    Type: String
    Description: Glue trigger that starts jobs & workflows
    AllowedValues:
      - dav_wc_check_summary_refresh_trigger_cfn
      - dav_wc_check_summary_refresh_trigger_cfn_prd

  GlueTrigger2:
    Type: String
    Description: Glue trigger that starts jobs & workflows
    AllowedValues:
      - dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY_trigger_cfn
      - dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY_trigger_cfn_prd

  GlueTrigger3:
    Type: String
    Description: Glue trigger that starts jobs & workflows
    AllowedValues:
      - dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY_trigger_cfn
      - dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY_trigger_cfn_prd

  GlueTrigger4:
    Type: String
    Description: Glue trigger that starts jobs & workflows
    AllowedValues:
      - dav_wc_load_onprem_to_s3_EXT_HFM312_DATA_trigger_cfn
      - dav_wc_load_onprem_to_s3_EXT_HFM312_DATA_trigger_cfn_prd

  GlueTrigger5:
    Type: String
    Description: Glue trigger that starts jobs & workflows
    AllowedValues:
      - dav_wc_load_s3_to_aurora_EXT_HFM312_DATA_trigger_cfn
      - dav_wc_load_s3_to_aurora_EXT_HFM312_DATA_trigger_cfn_prd

  GlueJob1:
    Type: String
    Description: Glue job for checking wdac schdule
    AllowedValues:
      - dav_wc_check_summary_refresh
      - dav_wc_check_summary_refresh_prd

  GlueJob2:
    Type: String
    Description: Glue job for checking wdac schdule
    AllowedValues:
      - dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY
      - dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY_prd

  GlueJob3:
    Type: String
    Description: Glue job for checking wdac schdule
    AllowedValues:
      - dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY
      - dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY_prd

  GlueJob4:
    Type: String
    Description: Glue job for checking wdac schdule
    AllowedValues:
      - dav_wc_load_onprem_to_s3_EXT_HFM312_DATA
      - dav_wc_load_onprem_to_s3_EXT_HFM312_DATA_prd

  GlueJob5:
    Type: String
    Description: Glue job for checking wdac schdule
    AllowedValues:
      - dav_wc_load_s3_to_aurora_EXT_HFM312_DATA
      - dav_wc_load_s3_to_aurora_EXT_HFM312_DATA_prd

  GlueRoleName:
    Type: String
    Description: IAM role for AWS Glue Job
    AllowedValues:
      - AWSGlueServiceRole-test
      - AWSGlueServiceRole-prod

  GlueConnection:
    Type: String
    Description: Data Connection for AWS Glue Job
    AllowedValues:
      - testconnection
      - prodconnection

  BucketName:
    Type: String
    Description: Bucket to store data
    AllowedValues:
      - workingcapitalphase1stgbucket
      - workingcapitalphase1prdbucket

Resources:
  # Glue Workflow
  workingcapitalsummaryworkflow:
    Type: 'AWS::Glue::Workflow'
    Properties:
      Description: Glue workflow that tracks specified triggers and jobs as a single entity
      Name: !Ref GlueWorkflowName

  # Glue Triggers
  checksummaryrefreshtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - workingcapitalsummaryworkflow
      - checksummaryrefresh
    Properties:
      Name: !Ref GlueTrigger1
      Type: ON_DEMAND
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: !Ref GlueJob1

  loadonpremtos3HFMLEGALENTITYtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - checksummaryrefreshtrigger
      - loadonpremtos3HFMLEGALENTITY
    Properties:
      Name: !Ref GlueTrigger2
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: !Ref GlueJob2
      Predicate:
        Conditions:
          - JobName: !Ref GlueJob1
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loads3toauroraHFMLEGALENTITYtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loadonpremtos3HFMLEGALENTITYtrigger
      - loads3toauroraHFMLEGALENTITY
    Properties:
      Name: !Ref GlueTrigger3
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: !Ref GlueJob3
      Predicate:
        Conditions:
          - JobName: !Ref GlueJob2
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loadonpremtos3EXTHFM312DATAtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loads3toauroraHFMLEGALENTITYtrigger
      - loadonpremtos3EXTHFM312DATA
    Properties:
      Name: !Ref GlueTrigger4
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: !Ref GlueJob4
      Predicate:
        Conditions:
          - JobName: !Ref GlueJob3
            LogicalOperator: EQUALS
            State: SUCCEEDED

  loads3toauroraEXTHFM312DATAtrigger:
    Type: 'AWS::Glue::Trigger'
    DependsOn: 
      - loadonpremtos3EXTHFM312DATAtrigger
      - loads3toauroraEXTHFM312DATA
    Properties:
      Name: !Ref GlueTrigger5
      Type: CONDITIONAL
      StartOnCreation: true
      WorkflowName: !Ref GlueWorkflowName
      Actions:
        - JobName: !Ref GlueJob5
      Predicate:
        Conditions:
          - JobName: !Ref GlueJob4
            LogicalOperator: EQUALS
            State: SUCCEEDED

  # Glue Jobs
  checksummaryrefresh:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJob1
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_check_summary_refresh.py
      GlueVersion: "4.0"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      NumberOfWorkers: 2
      WorkerType: G.1X
      DefaultArguments:  
        "--job-bookmark-option": "job-bookmark-disable"
        "--bucket_name": !Ref BucketName
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_check_summary_refresh.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/libraries/python_files.whl
        "--extra-jars": !Sub s3://${BucketName}/libraries/jar_files.jar

  loadonpremtos3HFMLEGALENTITY:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJob2
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Ref BucketName
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_onprem_to_s3_HFM_LEGAL_ENTITY.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/libraries/python_files.whl

  loads3toauroraHFMLEGALENTITY:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJob3
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Ref BucketName
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_s3_to_aurora_HFM_LEGAL_ENTITY.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/libraries/python_files.whl

  loadonpremtos3EXTHFM312DATA:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJob4
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_onprem_to_s3_EXT_HFM312_DATA.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Ref BucketName
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_onprem_to_s3_EXT_HFM312_DATA.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/libraries/python_files.whl

  loads3toauroraEXTHFM312DATA:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJob5
      MaxRetries: 0
      Role: !Ref GlueRoleName
      Command:
        Name: pythonshell
        PythonVersion: "3.9"
        ScriptLocation: !Sub s3://${BucketName}/scripts/dav_wc_load_s3_to_aurora_EXT_HFM312_DATA.py
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Connections: 
        Connections: 
          - !Ref GlueConnection
      DefaultArguments:  
        "--bucket_name": !Ref BucketName
        "--config_file_path": !Sub s3://${BucketName}/config/dav_wc_load_s3_to_aurora_EXT_HFM312_DATA.json
        "--TempDir": !Sub s3://${BucketName}/temporary/
        "--class": "GlueApp"
        "--extra-py-files": !Sub s3://${BucketName}/libraries/python_files.whl
